name: Build and Push to ECR

on:
  push:
    branches:
      - feature/docker

permissions:
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: cloud-security-posture-explorer

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Test Dependencies
        run: python -m pip install -r app/requirements-lock.txt

      - name: Check Bootstrap Syntax
        run: bash -n bootstrap.sh

      - name: Run Unit Tests
        run: python -m unittest discover -s app/tests -v

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::980468996827:role/GitHubActionsECRPushRole
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t $ECR_REPOSITORY:${{ github.sha }} .

      - name: Tag Docker Image
        run: |
          docker tag $ECR_REPOSITORY:${{ github.sha }} \
          980468996827.dkr.ecr.us-east-1.amazonaws.com/$ECR_REPOSITORY:${{ github.sha }}

      - name: Push Docker Image
        run: |
          docker push \
          980468996827.dkr.ecr.us-east-1.amazonaws.com/$ECR_REPOSITORY:${{ github.sha }}

      - name: Show Image Tag
        run: |
          echo "Image pushed:"
          echo "${{ github.sha }}"

  deploy-check:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: lab

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure deployment credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::980468996827:role/GitHubActionsPostureDeployRole
          aws-region: us-east-1

      - name: Verify deployment identity
        run: aws sts get-caller-identity